server:
  port: 8181

spring:
  application:
    name: eventhive

  datasource:
    url: jdbc:postgresql://localhost:5333/eventhive_dev
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    
  flyway:
    enabled: true
    repair: true
  
  jpa:
    hibernate:
        ddl-auto: validate
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        format_sql: true

eventhive:
  admin:
    email: ${ADMIN_EMAIL}
    password: ${ADMIN_PASSWORD}

jwt:
  secret: ${JWT_SECRET_KEY}
  